### ISSUE TITLE
Random nametag not working

### ISSUE THREAD

**Issue by 99IRock** [sgtcaze/NametagEdit#16] opened 2016-02-28 00:46 UTC
Hello,

Sometimes the per player nametag does not work. (The player just shows up with no prefix in the tablist). When I do /ne reload it's fixed.
Hope I gave you enough information,

Thanks in advance,
CB

**Comment by JustOneMoreBlock** [comment] 2016-02-28 02:09
Hello,

Are you using flat file? Such as groups.yml and players.yml? If so, can you provide your config files?

or MySQL? If it's mySQL, Can you provide a MySQL export of your database?

Are you using CraftBukkit/Spigot/Another version?
Type: /version in console.

Provide a list of your plugins.
Type: /pl in console.

**Comment by 99IRock** [comment] 2016-02-28 11:43
Flat File.

I'm using groups.yml and players.yml
The player is in players.yml (because he is an owner) and sometimes the name is white.
I don't know if this problem also happens if the player is not in the players.yml (Server is in alpha mode, not public at all)
players.yml
http://pastebin.com/jd5az3Ka
groups.yml
http://pastebin.com/gERGudkC

MC version:
This server is running CraftBukkit version git-Spigot-5f38d38-12698ea (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Plugins:
http://pastebin.com/tQUuQtWs

**Comment by sgtcaze** [comment] 2016-02-29 01:00
Please also include your config.yml as well. I noticed TagAPI is there, and this might be the source of some issues.

Edit: Will investigate further

**Comment by 99IRock** [comment] 2016-02-29 11:31
Sorry, forgot that one haha.
http://pastebin.com/4Bn5MJF8

I will delete iTag (TagAPI) since I used it for the same purpose as this plugin (I could only change color names with that).

Oh, iTag also creates a 'fake plugin' called TagAPI, because the original TagAPI was laggy and iTag replaced it and created the fake TagAPI so other plugins could work fine.

**Comment by sgtcaze** [comment] 2016-03-01 00:43
Did the removal of iTag have any effect?

**Comment by JustOneMoreBlock** [comment] 2016-03-05 22:17
Tested on Spigot 1.8.8
Added iTag
Added ProtocolLib (Required for iTag)

Findings:
Didn't find any errors and the plugin is working as intended with those plugins.

Since iTag is basically an API for support for another Nametag plugin. There may have been a conflict specifically to that Nametag plugin that uses iTag.

If the plugin has been removed and you still have iTag installed. There shouldn't be any conflicts. If the plugin you're using is there and prefer to use NametagEdit over that plugin then you should remove that Nametag plugin as well as iTag.

Closing the issue.

**Closed as completed by JustOneMoreBlock** 2016-03-05 22:17 UTC
Labels: Question
