### ISSUE TITLE
NameTagEdit got disabled! here is the error log

### ISSUE THREAD

**Issue by ZayanPlayz** [sgtcaze/NametagEdit#627] opened 2021-07-14 17:00 UTC
[click here for log error](https://paste.gg/p/anonymous/ad53c06ee8c0424c97735a6132f597e2)

Also this came: 

[20:57:04] [Server thread/ERROR]: [NametagEdit]
--
286 | ------------------------------------------------------
287 | [WARNING] NametagEdit v4.4.10 Failed to load! [WARNING]
288 | ------------------------------------------------------
289 | This might be an issue with reflection. REPORT this:
290 | > Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "com.nametagedit.plugin.packets.PacketWrapper.ChatComponentText" is null
291 | The plugin will now self destruct.
292 | ------------------------------------------------------

**Comment by Lorenzo0111** [comment] 2021-07-14 18:58
Please follow the issue format

**Comment by luca-mkbr** [comment] 2021-07-16 18:18
Same problem using 1.17, what is the format?

**Comment by Lorenzo0111** [comment] 2021-07-16 19:18
This probably is a duplicate of #621

**Comment by Aurelien30000** [comment] 2021-07-27 15:08
https://github.com/sgtcaze/NametagEdit/issues/631

**Comment by JustOneMoreBlock** [comment] 2021-08-08 08:28
This has been resolved in #633. Closes issue.

You can download the latest version here.

https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

- Supports: 1.8.x to 1.17.1
- HEX Code Support - Thanks to https://github.com/Lorenzo0111 and https://github.com/Aurelien30000
- Added `api-version`. Too many issues reported.
- Updated database to use jdbc instead.
- Updated our database to version 5. Alters the `prefix` and `suffix` tables to increase the `varchar` from 64 to 256.
- Many other bug fixes.

**Closed as completed by JustOneMoreBlock** 2021-08-08 08:28 UTC
