### ISSUE TITLE
WARN

### ISSUE THREAD

**Issue by ghost** [sgtcaze/NametagEdit#559] opened 2021-01-19 20:59 UTC
[17:53:00 WARN]: Legacy plugin NametagEdit v4.4.10 does not specify an api-version.

**Comment by Lorenzo0111** [comment] 2021-06-24 07:24
This is not a bug

**Comment by JustOneMoreBlock** [comment] 2021-08-08 08:39
This has been resolved in #633. Closes issue.

You can download the latest version here.

https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

- Supports: 1.8.x to 1.17.1
- HEX Code Support - Thanks to https://github.com/Lorenzo0111 and https://github.com/Aurelien30000
- Added `api-version`. Too many issues reported.
- Updated database to use jdbc instead.
- Updated our database to version 5. Alters the `prefix` and `suffix` tables to increase the `varchar` from 64 to 256.
- Many other bug fixes.

**Closed as completed by JustOneMoreBlock** 2021-08-08 08:39 UTC
