### ISSUE TITLE
Not worked in 1.17

### ISSUE THREAD

**Issue by WhiTe-Yak** [sgtcaze/NametagEdit#623] opened 2021-07-07 09:35 UTC
# Bug Report

**Type /ver NametagEdit and post the output.**

4.4.16

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

This server is running Paper version git-Paper-79 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: a831634)

**What plugins are you using? Type /plugins**

 Plugins (23): Chatty, CMI, CMILib, CoreProtect, DeluxeMenus, DiscordBot*, JetsAntiAFKPro, LuckPerms, NametagEdit*, OfflineManager, PlaceholderAPI, ProtocolLib, PvPManager, SignEdit, SkinsRestorer, TGConsole, TitleManager, UltimateAutoRestart, UltraCustomizer, Vault, WorldEdit, WorldEditSelectionVisualizer, WorldGuard

**Please explain your issue. How do you trigger it?**

Start server.

**Are there any errors in the console? Please use: https://pastebin.com**

https://pastebin.com/5azxDUN1

**Comment by Lorenzo0111** [comment] 2021-07-07 12:49
Duplicate of #621

**Comment by Aurelien30000** [comment] 2021-07-27 15:08
https://github.com/sgtcaze/NametagEdit/issues/631

**Comment by JustOneMoreBlock** [comment] 2021-08-08 08:17
This has been resolved in #633. Closes issue.

**Closed as completed by JustOneMoreBlock** 2021-08-08 08:17 UTC
