### ISSUE TITLE
Warn Loop Paper 1.17.1

### ISSUE THREAD

**Issue by Sergentval** [sgtcaze/NametagEdit#624] opened 2021-07-08 05:12 UTC
# Bug Report
Bug Loop in Paper 1.17.1

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.5.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
1.17.1 Paper 90

**What plugins are you using? Type /plugins**
AutoRestart*, BungeeTabListPlus, ChatControlRed, Chunky, ChunkyBorder, Citizens, CMI, CMILib, Denizen, DiscordSRV, dynmap, EasyBackup, EasyBackupCore, EasyCarts, FarmLimiter, Gringotts, HeadDatabase, HeadDisplays, Jobs, LiteBans, LuckPerms, LWC, LWCTrust, mcMMO, MysqlPlayerDataBridge, NametagEdit, NashornPlus, OpenAudioMc, PlaceholderAPI, ProtocolLib, Randomtp, SelectionVisualizer, Sentinel, ServersNPC, SimpleSorting, SurvivalInvisiframes, Towny, TownyGUI, Vault, WorldEdit, WorldGuard

**Please explain your issue. How do you trigger it?**
Run NameTagEdit on Paper 1.17.1

**Are there any errors in the console? Please use: https://pastebin.com**
https://pastebin.com/g5hASXSQ

**Comment by Lorenzo0111** [comment] 2021-07-08 07:07
Duplicate of #621

**Comment by Aurelien30000** [comment] 2021-07-27 15:08
https://github.com/sgtcaze/NametagEdit/issues/631

**Comment by JustOneMoreBlock** [comment] 2021-08-08 08:28
This has been resolved in #633. Closes issue.

You can download the latest version here.

https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

- Supports: 1.8.x to 1.17.1
- HEX Code Support - Thanks to https://github.com/Lorenzo0111 and https://github.com/Aurelien30000
- Added `api-version`. Too many issues reported.
- Updated database to use jdbc instead.
- Updated our database to version 5. Alters the `prefix` and `suffix` tables to increase the `varchar` from 64 to 256.
- Many other bug fixes.

**Closed as completed by JustOneMoreBlock** 2021-08-08 08:28 UTC
