### ISSUE TITLE
NPC Name Conflict

### ISSUE THREAD

**Issue by Lauris1988** [sgtcaze/NametagEdit#103] opened 2016-10-25 20:40 UTC
### What version/build of NametagEdit are you using? Type /ver NametagEdit

The Latest version of Nametagedit.
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver

 I'm using spigot 1.10.2 (Spigot-047f737-744e1a1)
### What plugins are you using? Type /plugins

Plugin list:  MinecraftMarket, WorldEdit, TerrainControl, PlaceholderAPI, zPermissions, ClearLag, FastCraftPlus, NametagEdit, JoinText, EasyBackup, Votifier, ProtocolLib, VoidSpawn, AdvancedPortals, AutomaticInventory, SkinsRestorer, eZProtector, FeatherBoard, HorseTpWithMe, CustomHelp, AntiAura, DontSpam, StaffPlus, CustomTab, HolographicDisplays, InfernalMobs, Essentials, EssentialsSpawn, Announcer, PremiumTurrets, WorldGuard, ChopTree3, EchoPet, RandomTeleport, GAListener, Feudal, DeluxeChat, Citizens, CommandNPC, LeaderHeads, CustomNoteBlock, Vault.
### Please explain your issue?

I have an issue with Tablist flickering with nearby NPC names in it. I use the latest version of Citizens plugin. NPC names in Tablist is disabled in Citizens config file. But I can still see name appearing and disappearing at random when I'm near NPCs. What is causing that and is is solvable?

**Comment by Abnormals** [comment] 2016-11-09 02:15
How do you make it where when someone is joining the server for their first time and they are put into a NameTagEdit group and when they hit tab their name is a different color or has like something in front of it or after it. How do you do that?

**Comment by Darlelet** [comment] 2016-12-14 23:56
Confirmed issue using Spigot 1.11 and latest NTE build, nearby NPCs seem to interfere with the plugin.

**Comment by Darlelet** [comment] 2016-12-19 21:44
Also when you log in an area and a NPC is standing close to your initial location, NTE just refuses to work, leaving the names white (by default). The only way to recover from this is by reloading the plugin or leaving the area and logging back in.

**Comment by TheWranger** [comment] 2016-12-26 04:58
This isn't an issue with NameTagEdit. This is an error with Citizens.

**Comment by Darlelet** [comment] 2016-12-26 10:50
Alright, thanks for the details. Any fix for this?

**Comment by TheWranger** [comment] 2016-12-27 01:02
Not that I've found. The glitch seems to be only affecting player NPCs though, so any skeleton or zombie npcs you make wont be affected.

**Comment by DutchUser** [comment] 2016-12-28 00:37
Bump, 

Have the same issue. Is there an fix!?

**Comment by Darlelet** [comment] 2016-12-28 00:53
Indeed. There seems to be a sloppy one though:

> Yup. For some drunk reason, Mojang made scoreboards use names, not UUIDs. So anything with the same name as you shares a scoreboard with you. Adding a color code to the end usually fixes that issue.

From https://github.com/CitizensDev/Citizens2/issues/963

**Comment by Darlelet** [comment] 2016-12-29 00:41
With that said, a good plugin option would be to specify a refresh rate for the tablist to prevent this kind of issue from "renaming" players (and thus remove any prefix / suffix associated with them). ATM you must reload NTE plugin in order to refresh the tablist, and that's kinda cumbersome IMO.

**Comment by sgtcaze** [comment] 2016-12-29 07:29
Perhaps an alternative is to listen for the outgoing packet that updates the tab list.

**Comment by TheWranger** [comment] 2016-12-29 07:31
Also, this isn't technically a "conflict", as you'll get this error even with nametagedit uninstalled

**Comment by Darlelet** [comment] 2016-12-29 09:30
@sgtcaze Looks like a good idea.

@TheWranger Yeah thanks, I got this ;) It still is bothersome when another plugin causes the tablist to refresh though.

**Comment by sgtcaze** [comment] 2017-03-11 08:34
Added this to the known caveats. We'll keep looking into fixes, but everything so far doesn't work.

**Closed as completed by sgtcaze** 2017-03-11 08:34 UTC
