### ISSUE TITLE
Gradle?

### ISSUE THREAD

**Issue by tomasweigenast** [sgtcaze/NametagEdit#574] opened 2021-03-05 15:31 UTC
I just wanna know if this has support for Gradle. Because im importing like so:
```
maven { 
    	url = 'http://ci.nametagedit.com/plugin/repository/everything/'
    }
```

```
compileOnly 'com.nametagedit:nametagedit:4.1.0'
```

And it does not work

**Comment by Lorenzo0111** [comment] 2021-06-24 06:09
The repository is currently offline

**Comment by Lorenzo0111** [comment] 2021-06-24 07:23
Also this is a duplicate of  #567

**Comment by JustOneMoreBlock** [comment] 2021-08-08 08:38
This is brought back online.

**Closed as completed by JustOneMoreBlock** 2021-08-08 08:38 UTC
