### ISSUE TITLE
nickname display option for tab

### ISSUE THREAD

**Issue by comfysquirrel** [sgtcaze/NametagEdit#23] opened 2016-03-22 19:02 UTC
I would like to be able to show player's nicknames in tab, and use the prefix/suffix nte feature in tab at the same time.

**Comment by JustOneMoreBlock** [comment] 2016-03-25 19:40
Yes, this is duplicate of #24.

Closing and will reference everything from there!

**Closed as completed by JustOneMoreBlock** 2016-03-25 19:40 UTC
