### ISSUE TITLE
error with new players 1.12

### ISSUE THREAD

**Issue by PhanaticD** [sgtcaze/NametagEdit#186] opened 2017-07-31 10:50 UTC
```
[06:49:15 WARN]: [NametagEdit] Task #172928 for NametagEdit v4.1.7 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.nametagedit.plugin.api.data.FakeTeam
        at com.nametagedit.plugin.NametagManager.addPlayerToTeam(NametagManager.java:53) ~[?:?]
        at com.nametagedit.plugin.NametagManager.setNametag(NametagManager.java:126) ~[?:?]
        at com.nametagedit.plugin.NametagManager.setNametag(NametagManager.java:122) ~[?:?]
        at com.nametagedit.plugin.NametagHandler$9.run(NametagHandler.java:410) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.jar:git-Paper-1168]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:832) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1168]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by sgtcaze** [comment] 2017-07-31 11:23
Just decompiled both jars for build 20, and the FakeTeam class is present. This is the first time I've seen this error with respect to NametagEdit, and to my knowledge it occurs when you use a PluginManager to dynamically load and unload. It doesn't always happen, but it happens when there are enough code changes.

Did this occur after a restart? Reload? Was NametagEdit functioning and then it suddenly stopped? Do you experience this issue on other servers using 4.1.7? 

Peculiar issue, but we'll find out the cause.

Edit: Perhaps corrupt jar from updating?

**Comment by PhanaticD** [comment] 2017-07-31 12:53
hmm not corrupt the jar size is 278991, all I did was start the server, however now I am not getting the error so I am not really sure what happened

**Comment by Seeroh** [comment] 2017-08-02 16:48
```[12:47:58] [Server thread/WARN]: [NametagEdit] Task #1082119 for NametagEdit v4.1.4 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.nametagedit.plugin.api.data.FakeTeam
	at com.nametagedit.plugin.NametagManager.addPlayerToTeam(NametagManager.java:54) ~[?:?]
	at com.nametagedit.plugin.NametagManager.setNametag(NametagManager.java:123) ~[?:?]
	at com.nametagedit.plugin.NametagHandler.applyTagToPlayer(NametagHandler.java:224) ~[?:?]
	at com.nametagedit.plugin.NametagHandler$4.run(NametagHandler.java:210) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[server.jar:git-Paper-1155]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [server.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:832) [server.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [server.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [server.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [server.jar:git-Paper-1155]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]


I get this when a player logs in, each time, doesn't seem to matter.

Using 4.1.4

**Comment by PhanaticD** [comment] 2017-08-02 16:50
race condition maybe? maybe check if somethings async that shouldnt be?

**Comment by sgtcaze** [comment] 2017-08-31 22:46
Are you guys still experiencing this issue? Apologies I was on vacation, could not work on this issue.

**Comment by PhanaticD** [comment] 2017-09-01 07:14
havent noticed it since then

**Comment by sgtcaze** [comment] 2017-10-13 23:29
Gonna close this since we've only seen one instance of this error, and it appears to have been resolved somewhere along the way. Most of the async/sync issues have been resolved, but we'll keep an eye out, definitely.

**Closed as completed by sgtcaze** 2017-10-13 23:29 UTC
